apiVersion: 0.2.3
builder:
  buildArgs:
    USE_CUDA: 'true'
  context: .
  dockerfile: ./Dockerfile
  image: mlebench
clone:
  depth: 1000
  includeDotGit: true
kind: AIchorManifest
spec:
  command: "entrypoint.sh /home/run.sh"
  debug:
    vscode:
      enabled: true 
      path: "/aichor/code" # Optional, defaults to "code". Refer the absolute path of the binary if not findable in $PATH
      provider: "github" # Optional,  vscode tunnel provider. Options are "github" or "microsoft", defaults to "github"
  image: mlebench
  operator: jax
  types:
    worker:
      count: 1
      resources:
        accelerators:
          gpu:
            count: 1
            product: NVIDIA-H100-80GB-HBM3
            type: gpu
        cpus: 96
        ramRatio: 20